// /robots.txt generated by Next.js App Router. Crawler allowlist per
// SITE_SPEC § 1.7: explicit allow for major search and AI crawlers
// (GPTBot, ClaudeBot, PerplexityBot, Google-Extended, anthropic-ai).

import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      { userAgent: '*', allow: '/' },
      { userAgent: 'GPTBot', allow: '/' },
      { userAgent: 'ClaudeBot', allow: '/' },
      { userAgent: 'PerplexityBot', allow: '/' },
      { userAgent: 'Google-Extended', allow: '/' },
      { userAgent: 'anthropic-ai', allow: '/' },
    ],
    sitemap: 'https://alexbacallao.com/sitemap.xml',
    host: 'https://alexbacallao.com',
  };
}
