// /sitemap.xml generated by Next.js App Router. URL list verbatim from
// SITE_SPEC § 1.7 "URL structure (locked)". Includes /resume.pdf as a
// locked URL even though it is a static asset, not an HTML page.
//
// `priority` and `changeFrequency` are not spec-locked; values reflect
// editorial weight (homepage > /projects > case studies > about/resume
// > contact). /contact bumped to 0.7 to flag its conversion role.

import type { MetadataRoute } from 'next';

const BASE = 'https://alexbacallao.com';
const LAST_MODIFIED = new Date('2026-04-29');

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: `${BASE}/`,                                 lastModified: LAST_MODIFIED, changeFrequency: 'monthly', priority: 1.0 },
    { url: `${BASE}/projects`,                         lastModified: LAST_MODIFIED, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE}/projects/ts-machines`,             lastModified: LAST_MODIFIED, changeFrequency: 'yearly',  priority: 0.8 },
    { url: `${BASE}/projects/nasa-circadian-lighting`, lastModified: LAST_MODIFIED, changeFrequency: 'yearly',  priority: 0.8 },
    { url: `${BASE}/projects/hackzurich-migros`,       lastModified: LAST_MODIFIED, changeFrequency: 'yearly',  priority: 0.8 },
    { url: `${BASE}/projects/nicular`,                 lastModified: LAST_MODIFIED, changeFrequency: 'yearly',  priority: 0.7 },
    { url: `${BASE}/projects/sofabot`,                 lastModified: LAST_MODIFIED, changeFrequency: 'yearly',  priority: 0.7 },
    { url: `${BASE}/about`,                            lastModified: LAST_MODIFIED, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/resume`,                           lastModified: LAST_MODIFIED, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/resume.pdf`,                       lastModified: LAST_MODIFIED, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${BASE}/contact`,                          lastModified: LAST_MODIFIED, changeFrequency: 'yearly',  priority: 0.7 },
  ];
}
