// /resume. Locked source: docs/pass2-resume.md (locked 2026-04-27).
//
// Two-format page pattern (SITE_SPEC.md section 1.9.7): this HTML page
// at /resume is the canonical web version (editorial typography, prose
// context, internal links to project pages). The PDF at /resume.pdf is
// hand-maintained by Alex - NOT auto-generated by the build pipeline -
// and lives at /public/resume.pdf as a static asset. Both share the
// "UPDATED APR 2026" date stamp; drift between them is the maintenance
// hazard for this page.
//
// Wink budget: ZERO protected winks. Resume is a no-wink genre per
// SITE_SPEC section 1.6 voice rule 5 / section 1.12.2 / pass2-resume.md
// section 6.13. Voice still applies (no LinkedIn-speak, sentence case,
// specific over abstract, no em dashes, no forbidden words), but humor
// is reserved for pages where it earns its place.
//
// Throughline: section 02 paragraph ships the locked Alex-verbatim
// phrase per spec section 6.3 ("shipping software to non-developers
// who need it to just work"). The SITE_SPEC section 1.11 verbatim-share
// claim with About is a drift logged in deviations.md from step 12.
//
// Phone is excluded from HTML and JSON-LD (PDF only). Email is in the
// top contact line as mailto link, but excluded from JSON-LD on this
// page (sitewide privacy pattern; only /contact exposes email in
// structured data). GitHub is excluded from the resume contact line
// (lives in global footer; resume contact stays minimal).
//
// Root layout owns <main>; this page returns a fragment. JSON-LD
// (ProfilePage with Person mainEntity) ships inline this step rather
// than waiting on build step 15 - schema is fully locked in spec
// section 6.11 and trivially serializable. See deviations.md for the
// formal entry.

import type { Metadata } from 'next';
import Link from 'next/link';
import { RevealOnScroll } from '../_components/RevealOnScroll';
import { RoleBulletList, type RoleBulletItem } from '../_components/RoleBulletList';
import { SectionDivider } from '../_components/SectionDivider';
import { MonoTable } from '../_components/MonoTable';
import { RoleEntry } from './_components/RoleEntry';

const PAGE_DESCRIPTION =
  'Software developer in Ft Worth, Texas. 4 years across embedded systems, healthcare, and industrial automation. Currently Digital Specialist at T&S Machines.';

export const metadata: Metadata = {
  title: 'Resume',
  description: PAGE_DESCRIPTION,
  alternates: {
    canonical: 'https://alexbacallao.com/resume',
  },
  openGraph: {
    title: 'Resume - Alex Bacallao',
    description: PAGE_DESCRIPTION,
    url: 'https://alexbacallao.com/resume',
    type: 'website',
  },
};

const SHELL = 'max-w-[880px] mx-auto px-5 md:px-8';

const profilePageJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'ProfilePage',
  name: 'Resume',
  url: 'https://alexbacallao.com/resume',
  isPartOf: {
    '@type': 'WebSite',
    name: 'Alex Bacallao',
    url: 'https://alexbacallao.com',
  },
  mainEntity: {
    '@type': 'Person',
    name: 'Alejandro Bacallao',
    alternateName: 'Alex Bacallao',
    jobTitle: 'Digital Specialist',
    worksFor: {
      '@type': 'Organization',
      name: 'T&S Machines and Tools',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Gainesville',
        addressRegion: 'TX',
        addressCountry: 'US',
      },
    },
    alumniOf: {
      '@type': 'CollegeOrUniversity',
      name: 'University of North Texas',
    },
    knowsLanguage: [
      { '@type': 'Language', name: 'English', alternateName: 'en' },
      { '@type': 'Language', name: 'Spanish', alternateName: 'es' },
      { '@type': 'Language', name: 'German', alternateName: 'de' },
    ],
    knowsAbout: [
      'Docker',
      'Python',
      'C',
      'C++',
      'C#',
      'JavaScript',
      'TypeScript',
      'Embedded Systems',
      'Industrial Automation',
      'Software Development',
      'HIPAA Compliance',
      'Arduino',
    ],
    homeLocation: {
      '@type': 'Place',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Ft Worth',
        addressRegion: 'TX',
        addressCountry: 'US',
      },
    },
    sameAs: [
      'https://linkedin.com/in/alejandrobacallao',
      'https://github.com/TacticalDoggo',
    ],
    award: [
      '1st place, Migros challenge, HackZurich 2022',
      '1st place, UNT Robotics Competition 2020',
      '3rd place, UNT Robotics Competition 2019',
    ],
  },
};

function HeaderSection() {
  return (
    <section
      id="header"
      aria-labelledby="header-heading"
      className={`${SHELL} pt-12 md:pt-16`}
    >
      <p className="mono-label text-text-muted mb-6">§ 01 - Resume</p>
      <h1 id="header-heading" className="mb-6">
        Resume
      </h1>
      <p className="max-w-[60ch] mb-6">
        The work history version. The longer story is on the{' '}
        <Link
          href="/about"
          className="text-accent no-underline hover:underline underline-offset-[3px]"
        >
          About page →
        </Link>
        .
      </p>
      <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-text-muted mb-4">
        <a
          href="mailto:alex.bacallao1996@gmail.com"
          className="text-text-muted no-underline hover:text-accent"
        >
          alex.bacallao1996@gmail.com
        </a>
        {' · '}
        <a
          href="https://linkedin.com/in/alejandrobacallao"
          className="text-text-muted no-underline hover:text-accent"
        >
          linkedin.com/in/alejandrobacallao
        </a>
        {' · '}
        Ft Worth, TX
      </p>
      <p>
        <a
          href="/resume.pdf"
          download
          className="text-[14px] font-medium text-accent no-underline hover:underline underline-offset-[3px]"
        >
          ↓ Download PDF (1 page)
        </a>
        <span className="mono-label text-text-muted ml-2">- Updated Apr 2026</span>
      </p>
    </section>
  );
}

function SummarySection() {
  return (
    <section
      id="summary"
      aria-labelledby="summary-heading"
      className={SHELL}
    >
      <p className="mono-label text-text-muted mb-6">§ 02 - Summary</p>
      <h2 id="summary-heading" className="mb-6">
        Summary
      </h2>
      <p className="max-w-[65ch]">
        Software developer with 4 years across embedded systems, healthcare,
        and industrial automation. The throughline has been shipping software
        to non-developers who need it to just work: CNC operators on a global
        shop floor, clinicians on a HIPAA-compliant patient-messaging system,
        spacecraft crew (in the senior-design version) on a circadian
        lighting controller. Most of that time has been at T&amp;S Machines:
        probing routines for CNC software, refactoring for stability,
        documentation and customer support, plus a Docker side project for
        cleaner deployment. Brief stint at Nicular in late 2022 building the
        patient-messaging system under HIPAA. Senior design at UNT was the
        NASA-sponsored circadian lighting controller. Won 1st place at
        HackZurich 2022 for a Migros supply-chain tool. Native Spanish and
        English, German A2/B1.
      </p>
    </section>
  );
}

function WorkSection() {
  return (
    <section
      id="work"
      aria-labelledby="work-heading"
      className={SHELL}
    >
      <p className="mono-label text-text-muted mb-6">§ 03 - Work</p>
      <h2 id="work-heading" className="mb-10">
        Work
      </h2>
      <div className="flex flex-col gap-12">
        <RoleEntry
          company="T&S Machines and Tools"
          role="Digital Specialist"
          dates="Dec 2023 - Present"
          location="Gainesville, TX (remote)"
          caseStudy={{
            label: 'CNC software at T&S Machines',
            href: '/projects/ts-machines',
          }}
        >
          <p>
            Refactored subroutines and improved screen-merging logic for
            stability. Authored and maintained the customer-facing technical
            documentation, distributed via GitLab, and provided remote
            technical support for issues in production environments.
            Containerized the application with Docker as a side initiative,
            exploring a cleaner deployment path than the manual installer
            process.
          </p>
        </RoleEntry>
        <RoleEntry
          company="Nicular"
          role="Software Developer"
          dates="Nov 2022 - Jan 2023"
          location="Remote (company in Dallas, TX)"
        >
          <p>
            Built an SMS and email reminder system for clinician workflows,
            integrating Vonage and GSuite APIs under HIPAA compliance.
            Designed the relational database schema for patient communication
            data. Contributed to a reusable communications framework that
            other workflows could adopt.
          </p>
        </RoleEntry>
        <RoleEntry
          company="T&S Machines and Tools"
          role="Software Developer"
          dates="Nov 2019 - Mar 2023"
          location="Gainesville, TX"
        >
          <p>
            Wrote and refactored probing and milling routines for CNC
            machines used by global customers. Built new probing functions
            and milling programs to customer spec. Maintained technical
            documentation for both CNC and balancing machine systems.
            Provided remote support for software issues in customer
            production environments.
          </p>
        </RoleEntry>
      </div>
    </section>
  );
}

function EducationSection() {
  return (
    <section
      id="education"
      aria-labelledby="education-heading"
      className={SHELL}
    >
      <p className="mono-label text-text-muted mb-6">§ 04 - Education</p>
      <h2 id="education-heading" className="mb-10">
        Education
      </h2>
      <article className="flex flex-col gap-3">
        <header className="flex flex-col gap-1">
          <div className="flex flex-col md:flex-row md:items-baseline md:justify-between md:gap-6">
            <p className="font-serif text-[22px] leading-[1.25] text-text-primary">
              University of North Texas - B.S. Computer Engineering, Minor in
              Mathematics
            </p>
            <p className="mono-label text-text-muted shrink-0">Dec 2023</p>
          </div>
          <p className="text-[14px] leading-[1.55] text-text-secondary">
            Denton, TX
          </p>
        </header>
        <p className="max-w-[65ch]">
          Senior design was the{' '}
          <Link
            href="/projects/nasa-circadian-lighting"
            className="text-accent no-underline hover:underline underline-offset-[3px]"
          >
            NASA-sponsored circadian lighting controller →
          </Link>
          . Coursework included embedded systems, computer architecture, and
          signal processing. Worked through college as a software developer
          at T&amp;S Machines.
        </p>
      </article>
    </section>
  );
}

const PROGRAMMING_LANGUAGES: ReadonlyArray<readonly [string, string]> = [
  ['C', 'C++'],
  ['C#', 'Python'],
  ['Java', 'JavaScript'],
  ['TypeScript', 'Bash'],
  ['PowerShell', 'Lua'],
  ['SQL', 'VHDL'],
  ['Assembly', ''],
];

const WEB_AND_MARKUP: ReadonlyArray<readonly [string, string]> = [
  ['Angular', 'React'],
  ['HTML', 'CSS'],
  ['XAML', 'YAML'],
  ['XML', ''],
];

const TOOLS_AND_PLATFORMS: ReadonlyArray<readonly [string, string]> = [
  ['Docker', 'Git · GitHub · GitLab'],
  ['MySQL', 'Xilinx Vivado'],
  ['IBM Rational Rhapsody', 'wxFormBuilder'],
  ['Actipro', 'Android Studio'],
  ['VS Code', 'Visual Studio'],
  ['Arduino', ''],
];

const SPOKEN_LANGUAGES: ReadonlyArray<readonly [string, string]> = [
  ['English', 'Native'],
  ['Spanish', 'Native'],
  ['German', 'A2 / B1'],
];

function SkillsSection() {
  return (
    <section
      id="skills"
      aria-labelledby="skills-heading"
      className={SHELL}
    >
      <p className="mono-label text-text-muted mb-6">§ 05 - Skills &amp; languages</p>
      <h2 id="skills-heading" className="mb-10">
        Skills and languages
      </h2>
      <div className="flex flex-col gap-8">
        <div>
          <p className="font-medium text-[14px] text-text-primary mb-3">
            Programming languages
          </p>
          <MonoTable rows={PROGRAMMING_LANGUAGES} ariaLabel="Programming languages" />
        </div>
        <div>
          <p className="font-medium text-[14px] text-text-primary mb-3">
            Web &amp; markup
          </p>
          <MonoTable rows={WEB_AND_MARKUP} ariaLabel="Web and markup" />
        </div>
        <div>
          <p className="font-medium text-[14px] text-text-primary mb-3">
            Tools &amp; platforms
          </p>
          <MonoTable rows={TOOLS_AND_PLATFORMS} ariaLabel="Tools and platforms" />
        </div>
        <div>
          <p className="font-medium text-[14px] text-text-primary mb-3">
            Spoken languages
          </p>
          <MonoTable
            rows={SPOKEN_LANGUAGES}
            headers={['Language', 'Level']}
            ariaLabel="Spoken languages"
          />
        </div>
      </div>
    </section>
  );
}

const AWARDS: RoleBulletItem[] = [
  {
    lede: '1st place, HackZurich 2022, Migros challenge.',
    description: '36-hour international hackathon, Zurich. Team of 5.',
  },
  {
    lede: '1st place, UNT Robotics Competition 2020.',
    description: 'Arduino-based robotics challenge.',
  },
  {
    lede: '3rd place, UNT Robotics Competition 2019.',
    description: 'Arduino-based robotics challenge.',
  },
];

function AwardsSection() {
  return (
    <section
      id="awards"
      aria-labelledby="awards-heading"
      className={SHELL}
    >
      <p className="mono-label text-text-muted mb-6">§ 06 - Awards</p>
      <h2 id="awards-heading" className="mb-6">
        Awards
      </h2>
      <RoleBulletList items={AWARDS} />
    </section>
  );
}

const PROJECTS: RoleBulletItem[] = [
  {
    lede: 'CNC software at T&S Machines →',
    ledeHref: '/projects/ts-machines',
    description:
      "Four years writing and maintaining the software that runs T&S Machines' CNC controllers, plus a Docker side project for cleaner deployment. C#, WPF, Docker, GitLab CI. Ongoing.",
  },
  {
    lede: 'NASA Circadian Lighting →',
    ledeHref: '/projects/nasa-circadian-lighting',
    description:
      'Closed-loop spacecraft lighting controller, Texas Space Grant senior design. Python, Raspberry Pi 4, OLA over DMX-512. Spring 2022.',
  },
  {
    lede: 'Supply chain rerouting at HackZurich →',
    ledeHref: '/projects/hackzurich-migros',
    description: (
      <>
        36-hour hackathon project for Migros: web tool for shipping route
        recommendations. React, Python, Jupyter.{' '}
        <strong className="font-semibold italic">
          1st place, Migros challenge.
        </strong>{' '}
        2022.
      </>
    ),
  },
];

function ProjectsSection() {
  return (
    <section
      id="projects"
      aria-labelledby="projects-heading"
      className={SHELL}
    >
      <p className="mono-label text-text-muted mb-6">§ 07 - Projects</p>
      <h2 id="projects-heading" className="mb-6">
        Projects
      </h2>
      <RoleBulletList items={PROJECTS} />
      <p className="max-w-[65ch] mt-6">
        Also: a HIPAA-compliant patient messaging system at Nicular (Vonage,
        GSuite, 2022), and SofaBot from the UNT robotics club.
      </p>
    </section>
  );
}

export default function ResumePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(profilePageJsonLd),
        }}
      />
      <HeaderSection />
      <SectionDivider />
      <RevealOnScroll>
        <SummarySection />
      </RevealOnScroll>
      <SectionDivider />
      <RevealOnScroll>
        <WorkSection />
      </RevealOnScroll>
      <SectionDivider />
      <RevealOnScroll>
        <EducationSection />
      </RevealOnScroll>
      <SectionDivider />
      <RevealOnScroll>
        <SkillsSection />
      </RevealOnScroll>
      <SectionDivider />
      <RevealOnScroll>
        <AwardsSection />
      </RevealOnScroll>
      <SectionDivider />
      <RevealOnScroll>
        <ProjectsSection />
      </RevealOnScroll>
      <SectionDivider />
    </>
  );
}
